### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Solution

- *[14.0.0](https://about.gitlab.com/releases/2021/06/22/gitlab-14-0-released/)*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by Christophe31** [comment]
Not sure what's in but there is already a bug/regression fixes release, not marked as a security release.

**Comment by kay0u** [comment]
@Christophe31 Yes but this release [is not available for rpi 2](https://packages.gitlab.com/gitlab/raspberry-pi2)

It's not the first time, I have already [reported this several times](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5520). One day I'll just make a PR to unlink the rpi 2 version from the others I think

**Comment by Christophe31** [comment]
If we only skip some minors which are not critical security release it's not a big issue I think (at least I don't see usecases where it may bother anyone to have up to a month or two of wait to have a release)… But I didn't know about the rpi2 issue, thx for the info. I didn't event checked if there are regressions which are real issues but we may as well wait for a later release if it's the case…

**Pull request merged**
