### PR TITLE
Upgrade to 11.11.1

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *[Vulnerability](https://about.gitlab.com/2019/06/03/security-release-gitlab-11-dot-11-dot-1-released/)*

## Solution
- *Upgrade to 11.11.1*
- *Add some doc*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/gitlab_ynh%20(Kay0u)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
What are your feedback from the CI ?
I had many errors with the backup and change_url script

**Comment by kay0u** [comment]
My CI is running, and I change the URL of the badge for the ci-apps-dev for now...

**Comment by kay0u** [comment]
Well, I only have a warning during the restore:
```
FAILED: Failed to connect to internal API
```
After a restart of gitlab, this one should disappear

**Comment by kay0u** [comment]
For what I've read, it shouldn't really be a problem... I propose to merge it anyway, because version 11.11.0 has a vulnerability problem.

**Comment by maniackcrudelis** [comment]
The CI dev succeed, it could have been an issue with my VM.
Let's merge in 3 days

**Pull request merged**
