### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Comment by rodinux** [comment]
Hello, is it really necessary keep the test from this commit https://github.com/YunoHost-Apps/gitlab_ynh/commit/722fa8db9d8d840064ffc64338e1170da7cafc37 ? it seems be outdated. 
The upgrade seems brake only with this test 
https://github.com/YunoHost-Apps/gitlab_ynh/blob/08921c71303779b8b6ec09180eff11f24f71cc6e/tests.toml#L8C5-L8C26
Regards

**Comment by kay0u** [comment]
I'd like to know why there is an issue on this test. Feel free to upgrade it via ssh if you want this new version

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Pull request merged**
