### PR TITLE
13.12.0

### PR DESCRIPTION
**Pull request by kay0u**
## Solution

- *[13.12.0](https://about.gitlab.com/releases/2021/05/22/gitlab-13-12-released/)*
- *[13.12.1](https://about.gitlab.com/releases/2021/05/25/gitlab-13-12-1-released/)*
- *Use `ynh_add_config`*
- *Use auto generated readme*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Review by yalh76 — APPROVED** [review]
Quick review, LGTM

**Pull request merged**
