### PR TITLE
Testing

### LINKED ISSUE #103: git clone git@... asks for password also if ssh key is added
I added a ssh key in gitlab.
then try to clone a repository created from web ui with
`git clone git@...`
output is
```
Cloning into 'repositoryname'...
Debian GNU/Linux 9
git@...'s password: 
Permission denied, please try again.
git@...'s password: 
Permission denied, please try again.
git@...'s password: 
git@...: Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
the output of `ssh -vT git@...` is
```
OpenSSH_8.2p1, OpenSSL 1.1.1e  17 Mar 2020
debug1: Reading configuration data /home/luigi/.ssh/config
debug1: /home/luigi/.ssh/config line 4: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to ... [...] port 22.
debug1: Connection established.
debug1: identity file /home/luigi/.ssh/id_rsa type -1
debug1: identity file /home/luigi/.ssh/id_rsa-cert type -1
debug1: identity file /home/luigi/.ssh/id_dsa type -1
debug1: identity file /home/luigi/.ssh/id_dsa-cert type -1
debug1: identity file /home/luigi/.ssh/id_ecdsa type -1
debug1: identity file /home/luigi/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/luigi/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/luigi/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/luigi/.ssh/id_ed25519 type 3
debug1: identity file /home/luigi/.ssh/id_ed25519-cert type -1
debug1: identity file /home/luigi/.ssh/id_ed25519_sk type -1
debug1: identity file /home/luigi/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/luigi/.ssh/id_xmss type -1
debug1: identity file /home/luigi/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4p1 Debian-10+deb9u7
debug1: match: OpenSSH_7.4p1 Debian-10+deb9u7 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to ...:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:1y91yPdiM2BOkqmxbUBeTCL0GmpAdvMJwQTUObUcU+w
debug1: Host 'uno.detuning.org' is known and matches the ECDSA host key.
debug1: Found key in /home/luigi/.ssh/known_hosts:7
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/luigi/.ssh/id_rsa 
debug1: Will attempt key: /home/luigi/.ssh/id_dsa 
debug1: Will attempt key: /home/luigi/.ssh/id_ecdsa 
debug1: Will attempt key: /home/luigi/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/luigi/.ssh/id_ed25519 ED25519 SHA256:gQPcsZKZz94iY/wCVm+moWYtm1gUReqs5gavd4291qA
debug1: Will attempt key: /home/luigi/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/luigi/.ssh/id_xmss 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
Debian GNU/Linux 9
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Trying private key: /home/luigi/.ssh/id_rsa
debug1: Trying private key: /home/luigi/.ssh/id_dsa
debug1: Trying private key: /home/luigi/.ssh/id_ecdsa
debug1: Trying private key: /home/luigi/.ssh/id_ecdsa_sk
debug1: Offering public key: /home/luigi/.ssh/id_ed25519 ED25519 SHA256:gQPcsZKZz94iY/wCVm+moWYtm1gUReqs5gavd4291qA
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /home/luigi/.ssh/id_ed25519_sk
debug1: Trying private key: /home/luigi/.ssh/id_xmss
debug1: Next authentication method: password
git@...'s password: 
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
git@...'s password: 
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
git@...'s password: 
debug1: Authentications that can continue: publickey,password
debug1: No more authentication methods to try.
git@...: Permission denied (publickey,password).
```

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *#103*

## Solution
- *[12.9.1](https://about.gitlab.com/releases/2020/03/26/security-release-12-dot-9-dot-1-released/)*
- *Fix #103*
- *[12.9.2](https://about.gitlab.com/releases/2020/03/31/gitlab-12-9-2-released/)*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** :  Maniack C
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/gitlab_ynh%20PR104%20(Kay0u)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by kay0u** [comment]
bump

**Comment by maniackcrudelis** [comment]
> - [ ] Can be reviewed and tested.

**Comment by kay0u** [comment]
Thank you (sorry always forgot about it)

**Comment by kay0u** [comment]
Merging in 3 days

**Pull request merged**
