### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Solution
- *[13.9.0](https://about.gitlab.com/releases/2021/02/22/gitlab-13-9-released/)*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** :  
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
```
Package linter:                OK 
Install (root):                OK 
Install (subdir):              OK 
Install (private):             OK 
Backup/restore:                OK 
Upgrade:                       OK 
Upgrade (2cc84310):            OK 
Upgrade (7c352aff):            OK 
Change url:                    OK 
Port already used (8080):      OK 

Level results
=============
Level 1 (Installable in at least one scenario)    OK 
Level 2 (Installable in all scenarios)            OK 
Level 3 (Can be upgraded)                         OK 
Level 4 (Can be backup/restored)                  OK 
Level 5 (No linter errors)                        OK 
Level 6 (App is in a community-operated git org)  OK 
Level 7 (Pass all tests + no linter warnings)     OK 
Level 8 (Maintained and long-term good quality)   OK 
Level 9 (Flagged high-quality in app catalog)     OK
```

On my side

**Review by yalh76 — APPROVED** [review]

**Pull request merged**
