### PR TITLE
12.0.3

### PR DESCRIPTION
**Pull request by kay0u**
## Solution
- *12.0.3*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/gitlab_ynh%20(Kay0u)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
I suppose that the same PR than it was previously, otherwise, please provide another link for the CI.

**Comment by kay0u** [comment]
Yep it's the same, should I wait 3 days again?

**Comment by maniackcrudelis** [comment]
Best thing to do would be to advertise this testing release and hope for people to try it. As we do for Official apps.

**Comment by kay0u** [comment]
We can wait a little while, but there is a critical issue in current packaged version:

https://about.gitlab.com/2019/07/03/security-release-gitlab-12-dot-0-dot-3-released/

**Comment by maniackcrudelis** [comment]
It's not just a small upgrade, there's a little bit much in that PR.
But not that much though and as I can read the current version is affected by this security issue.
Also, I'm not sure we have that many users for now on this app.

Haven't seen before your post on the forum. Great.
As it's a security matter, let's say we can merge in 3 days :wink:.

**Comment by kay0u** [comment]
If you want to wait a little while before merging this PR, I can just update master with version 11.11.5. I just have to modify 2 sha256, the manifest, and the readme (I can create a PR from branch 11.11.5 to master).

The upgrade works on my server though.

> Haven't seen before your post on the forum. Great.
Yup, I never updated before, but it's here \o/

**Comment by maniackcrudelis** [comment]
Never mind, let's merge.

**Pull request merged**
